### ISSUE TITLE
youtube media source should use "embed" instead of "watch" pathname

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-backend#146]
In GitLab by @stefanprobst on Jan 17, 2022, 19:41

afaiu the database is initially populated with two media sources for youtube and vimeo, with media category "EMBED", and a `serviceUrl` which uses `watch` as the pathname. however, URLs like https://www.youtube.com/watch?v=dQw4w9WgXcQ can *not* be embedded in an iframe. instead we should use "embed" in the pathname, e.g. https://www.youtube.com/embedv=dQw4w9WgXcQ.

i think this would need to be changed [here](https://gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/-/blob/develop/src/main/resources/initial-data/basic-data.yml#L291) (?)

EDIT: i did change the service url for the youtube media source in the prod db, but not sure what to do to change the category of already existing media (i.e. youtube urls)

**Comment by KlausIllmayer** [comment]
Seems that the issue was closed without fixing it. It does not have high priority, because the endpoint can be changed manually (`PUT /api/media-sources/youtube`), but nevertheless it would be good to adapt it in the code. Should be a simple search for `youtube.com/watch` and replace with `youtube.com/embed`. I see the mentioned entry in the [initial-data](https://gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/-/blob/develop/src/main/resources/initial-data/basic-data.yml#L291) which I could have changed by myself but there are also some tests in place, where the `youtube.com/watch` is used, e.g. [here](https://github.com/SSHOC/sshoc-marketplace-backend/blob/develop/src/test/java/eu/sshopencloud/marketplace/controllers/media/MediaUploadControllerITCase.java#L696). Maybe it is worth to have a more detailed look on these tests.

**Comment by tparkola** [comment]
In the migration script db/changelog/migrations/0057-SSHOC_146-yt_url_change.yaml the service_url in media_sources table is already changed to proper value. We can add additional script that will update all source_url in media_data, however, this won't fully solve the problem. The reason is that it is a user who provides a link to the media. So, if the user will use a link with "watch", then we encounter the same problem. We can (1) leave it as is (but it may cause similar inconsistencies in the future if users are not aware) or we can (2) add additional validation in the backend - additional validation would require discussion / agreement on how to approach that, because each media source may need different approach. In case of (2) a new task would be needed, as this will probably be a medium task, not a small one.

**Comment by laureD19** [comment]
curation and front-end to support these "embbed" links: curation to check current links and front-end to add help text
