### ISSUE TITLE
Endpoint for contributed items per user.

### ISSUE THREAD

**Issue by dpancic** [SSHOC/sshoc-marketplace-backend#168]
In GitLab by @tparkola on May 13, 2022, 08:33

Regarding to what we discussed in the meeting, I created an endpoint (`GET /api/contributed-items`) that returns the current list of BasicItemDtos, that user has contributed to. 
The changes are merged to dev. 
@vronk @laureD19 @KlausIllmayer @stefanprobst

**Comment by KlausIllmayer** [comment]
I can confirm, that the `/api/contributed-items` delivers now back the latest version of all the items that were approved/suggested/ingested. But it neither gives an option to only show such a list based on the status (e.g. show me only the items with the status approved) nor does it give the information about the status in the response value (there is only id/category/label/persistentId/lastInfoUpdate but no status).

I agree with Stefan that we could get rid of the status boxes in the "My contributed items" as the difference between "approved" and "suggested" is not really explainable and "ingested" is a very special status, which usually only few users will ever see. But to have a clue, I would prefer to add the status in the response so that it can be shown in the frontend. @tparkola Can you add the status in the respone of `GET /api/contributed-items`? Then I would hand it over to frontend.

**Comment by KlausIllmayer** [comment]
Tested it and the results do look reliable. I see for two tested accounts the contributed items where there was once an activity but in the meantime some other account performed another activity, which currently do not show up but can be seen in the new endpoint. There is also the information on the current status in the payload.

Frontend can in my opinion now use this endpoint to replace the old contributed items view with the result set coming from the endpoint `GET /api/contributed-items`.
