### ISSUE TITLE
Revert deleting of an item

### ISSUE THREAD

**Issue by KlausIllmayer** [SSHOC/sshoc-marketplace-backend#435]
Long time ago we discussed the possibility to revert a deleted item back to an active state in MP: https://gitlab.gwdg.de/sshoc/sshoc-marketplace-backend/-/issues/163
We tried to find a way to revert such a deleted item but we were not successful. It seems, that this is not implemented or is blocked by 404 errors.
What we tried:
* `GET /api/deleted-items` and find the persistentId and versionId (remark: there are problems with this endpoint regarding the order-parameter, which does not work proper at least for the `label` value; additionally, I have problems when trying to get to the last page: it will show further pages, but only on the last page and I can also put high numbers inside the page-value, e.g. 55 which will then open the page 5 - maybe something to look more into, otherwise it is not easy to find a deleted item - btw: a search for label would be great)
* try `PUT /api/tools-services/{persistentId}/versions/{versionId}/revert` but delivers a 404 error
* try `PUT `/api/tools-services/{persistentId}` gives also a 404 error

I don't see any further endpoints that could do the trick. @tparkola Can you look into the code, if we miss something or if the revert of deleted items is simple not implemented.

Notify @laureD19 about the issue

**Comment by laureD19** [comment]
blocking curation work (and the need to delete ~1000 items)

**Comment by tparkola** [comment]
After quick investigation I see that deleted item is treated as non-existent in many cases (kind of understandable), hence:
- you cannot revert on non-active/deleted items, so this is why you get 404 when trying to revert version of a deleted item (system sees that the item you want to revert does not exist, so 404)
- you cannot update deleted item, so this is why you get 404 (because the system does not find any active item that could be updated, as the one you want to update is indeed deleted)
- you cannot undelete and item (make it active again), not sure if it was intentional not to allow undelete (do you know that by chance?).

Anyway we can start maybe with the intention you have when working with items - why would you during the curation work first delete an item and then wanted to have it back again, especially considering ~1000 items? We could also have a short call about that.

**Comment by laureD19** [comment]
thanks for looking into this Tomasz! 

Reasons to revert deleted items:
- error from the admin when deleting an item (case-by-case basis) 
- some items were ingested from the dblp source to conduct an experiment - to check the presence of tools in these publications to create relations - and now we don't want anymore the items without any relations, but it could be that we want to bring them back to life at some point in the future
- some items were ingested - from TaPoR - but are outdated tools that we have decided not to keep in the MP. They are still of interest for the community and it could be that editorial line of the MP changes in the future, and that we want to bring the "historial" items back to life.

Does it help?
In that regard, I think it would be important to allow to revert the last version of a deleted item to a new version with an `approved` status

**Comment by KlausIllmayer** [comment]
It could work like this: we agree that reverting an item does set it always to APPROVED and the administrators doing this revert need to be aware about this (that is not very clean but a pragmatic approach)

**Comment by tparkola** [comment]
Done. Only admin can revert. When reverting: item's status is set to APPROVED, its versioned item's status is set to REVIEWED, and its active param is set to true.
