### ISSUE TITLE
Log files missing and terminal/shell is not available

### ISSUE THREAD

**Issue by KlausIllmayer** [SSHOC/sshoc-marketplace-backend#461]
Most probably after updating to a new java/springboot version we lost on our Kubernetes cluster the possiblity to see the logs and to enter the terminal/shell of the API container as well as the solr container.

@tparkola Is this something you can confirm on your local development instance? Did something changed in the behaviour of the container regarding logs and shell when we switched to eclipse-temurin:21?

**Comment by tparkola** [comment]
It should work fine. I saw on your platform that I can access logs and terminal. Not sure what is the problem when you try to use it. What I only saw (that could be corrected) is that in the https://github.com/SSHOC/sshoc-marketplace-backend/blob/develop/Dockerfile-acdh-ch on line 21 there is `--logging.file=/log/sshoc-marketplace-backend-app.log` but it should be `--logging.file.name=/log/sshoc-marketplace-backend-app.log` (newer version of spring changed the way you indicate logging file name). However, I think this is not something that currently is a problem because I see log file properly updated. As I mentioned - I see in your environment logs and can access terminal. Maybe you would need to let me know what does not work for you exactly. Maybe I misunderstood something. Hope that helps.

**Comment by KlausIllmayer** [comment]
Changed the logging-parameter, thanks for noticing.
The other problem is unclear. Now everything works. Asking our sysadmins they are also not sure but maybe it was then an issue with the Kubernetes cluster. Lets hope, that it will not raise again, but most probably it is then a problem on side of the Kubernetes cluster.
Thanks for looking into it
